SPACE_LIMIT = 5
POPULATION_SIZE = 100
GENERATIONAL_LEAP = 0.7
NUMBER_OF_GENERATIONS = 200
MUTATION_PROBABILITY = 0.1
#CROSSOVER_FUNCTION VALUES:
#   "RANDOM": cruza binomial aleatoria
#   "SINGLE_POINT": cruza simple
#   "MASK": cruza binomial con máscara doble
CROSSOVER_FUNCION = "MASK"
#MASKS
MASK_FIRST_CHILD = "XXYYXYXXXYYYXYXYYYXX"
MASK_SECOND_CHILD = "YYXXYXYYYXXXYXYXXXYY"

